### ISSUE TITLE
Navigator and DefaultNavigator shoul not handle userStatusChanged

### ISSUE THREAD

**Issue by lelmarir** [davidsowerby/krail#318]
The default navigator should not handle the login of a user. The login page itself should do it.

Currently after the login page the user is redirected to the previous page or the default one, but this would not be the correct behaviour if the login happen with a different method, eg. an embedded login form in the right top corner of the page. In this case the page should stay the same and be informed about the changed user status (or refresh)

**Comment by davidsowerby** [comment]
When a user logs in (by any method), the Navigator has the opportunity to respond by navigating to a new page.  At the moment this behaviour is fixed, as you say - and also therefore potentially incorrect for the case you describe.  I intended to allow for a landing page after login, but the solution is too rigid. I think this could be solved with some configuration options to allow the developer to select behaviour on login:

- log in landing page url (instead of the fixed default)
- boolean:  alwaysNavigateToLandingPage ...navigate to landing page even if already on a page

When a user logs out, it is required that the user does not stay on a page which is not public.  An option could be added for logout behaviour

- alwaysNavigateToLogoutPage - if false, change page only if the current page is private

Would these resolve the issue?

**Comment by lelmarir** [comment]
It could, but i think it will violate the single responsibility principle.

i think that the login page itself should handle the navigation after the login.
Maybe the navigation after the login could be based on the logged in user, or an option selected during the login.

The log out could be handled by the navigator because this is a security concern.

**Comment by davidsowerby** [comment]
I agree with the principle but surely the only responsibility of the login page is to authenticate the user?

Responsibility for navigation, of course, rests with the Navigator

**Comment by davidsowerby** [comment]
I think the other points you make are good, though, including the suggestion that there may need to be a different response for different users, or a choice by the user during the login.

Instead of just having configuration options, I think the best way to make that configurable is to use "rules":

- LoginNavigationRule
- LogoutNavigationRule

These would be interfaces with default implementations, but it would allow a Krail developer to apply whatever rules they wish to respond to login / logout

**Comment by lelmarir** [comment]
this could be a solution, but the rule should not be global, but based on the current page:

if the application has 2 login methods (login page as now, and embedded login in the right top corner) the rule should be based on which logging method would be used.
And the rule can't handle it by distinguish between the two sources, because they are two different things and should not know each other

**Comment by davidsowerby** [comment]
>And the rule can't handle it by distinguish between the two sources, because they are two different things and should not know each other

I'll think about it more when I implement it, but a rule would need context in order to make a decision - I think that the source, the navigation state and user information are all needed.  

The source will be able to determine which rule to use, and pass it to the Navigator to act on.

This will keep the rules independent.   There could be a different rule for each source or a generic rule for all sources, whichever the developer wants.
